/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscribeRouteImport } from './routes/transcribe'
import { Route as FineTuneRouteImport } from './routes/fine-tune'
import { Route as CreateDatasetRouteImport } from './routes/create-dataset'
import { Route as IndexRouteImport } from './routes/index'

const TranscribeRoute = TranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const FineTuneRoute = FineTuneRouteImport.update({
  id: '/fine-tune',
  path: '/fine-tune',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDatasetRoute = CreateDatasetRouteImport.update({
  id: '/create-dataset',
  path: '/create-dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-dataset': typeof CreateDatasetRoute
  '/fine-tune': typeof FineTuneRoute
  '/transcribe': typeof TranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-dataset': typeof CreateDatasetRoute
  '/fine-tune': typeof FineTuneRoute
  '/transcribe': typeof TranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-dataset': typeof CreateDatasetRoute
  '/fine-tune': typeof FineTuneRoute
  '/transcribe': typeof TranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-dataset' | '/fine-tune' | '/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-dataset' | '/fine-tune' | '/transcribe'
  id: '__root__' | '/' | '/create-dataset' | '/fine-tune' | '/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateDatasetRoute: typeof CreateDatasetRoute
  FineTuneRoute: typeof FineTuneRoute
  TranscribeRoute: typeof TranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcribe': {
      id: '/transcribe'
      path: '/transcribe'
      fullPath: '/transcribe'
      preLoaderRoute: typeof TranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-tune': {
      id: '/fine-tune'
      path: '/fine-tune'
      fullPath: '/fine-tune'
      preLoaderRoute: typeof FineTuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-dataset': {
      id: '/create-dataset'
      path: '/create-dataset'
      fullPath: '/create-dataset'
      preLoaderRoute: typeof CreateDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateDatasetRoute: CreateDatasetRoute,
  FineTuneRoute: FineTuneRoute,
  TranscribeRoute: TranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
